"""Joint Gaussian reference imputer (Schafer 1997's NORM with regressors).

The analytically transparent backend: participant i's response vector over
the J design waves follows a multivariate regression

    Y_i = B' x_i + e_i,        e_i ~ N(0, Sigma),

with participant-level predictors x_i (intercept added automatically),
wave-specific coefficients for every predictor, and unstructured Sigma.
Because every predictor gets its own coefficient at every wave, the mean
model is fully saturated in time: exposure-by-wave interactions are always
present (A8), and any analysis linear in these predictors and time is
nested in the imputation model.

Imputations are posterior-predictive draws (Proposition 2) generated by
Tanner-Wong data augmentation with the *exact* conjugate conditionals under
the Jeffreys prior p(B, Sigma) ~ |Sigma|^-(J+1)/2:

    I-step:  Y_mis | B, Sigma      — conditional multivariate normal
    P-step:  Sigma | Y_complete    ~ InverseWishart(n - K, S)
             B | Sigma, Y_complete ~ MatrixNormal(B_hat, (X'X)^-1, Sigma)

Both parameter and outcome uncertainty are propagated (A6). Successive
kept imputations are separated by `thin` sweeps after an initial `burn_in`;
they are draws from one chain, so `thin` should be large enough that
imputations are effectively independent (the default is conservative for
the small fixed-wave problems this backend targets).

Scope: continuous outcomes; a complete participant-by-wave row grid
(missing outcomes allowed, missing rows not); predictors constant within
participant. Time-varying predictors need the GLMM backends.
"""

from __future__ import annotations

import numpy as np
from scipy import stats

from ..contracts import ValidityDeclaration
from ..data import CompletedDatasetCollection, LongitudinalData
from ..scenarios import DeltaAdjustment
from .base import BaseImputer

__all__ = ["JointGaussianImputer"]


class JointGaussianImputer(BaseImputer):
    """Posterior-predictive joint Gaussian imputation for fixed-wave data.

    Parameters
    ----------
    burn_in:
        Data-augmentation sweeps discarded before the first kept imputation.
    thin:
        Sweeps between successive kept imputations.
    delta:
        Optional :class:`DeltaAdjustment` applied to imputed values (MNAR
        sensitivity). For the identity link the ``linear_predictor`` and
        ``outcome`` scales coincide: imputed draws are shifted by ``delta``.
    """

    def __init__(
        self,
        *,
        burn_in: int = 500,
        thin: int = 100,
        delta: DeltaAdjustment | None = None,
    ) -> None:
        if burn_in < 0 or thin < 1:
            raise ValueError("burn_in must be >= 0 and thin >= 1")
        self.burn_in = burn_in
        self.thin = thin
        self.delta = delta

    @property
    def declaration(self) -> ValidityDeclaration:
        return ValidityDeclaration(
            missingness_assumption=(
                "MAR" if self.delta is None else f"MNAR(delta={self.delta.delta})"
            ),
            mar_empirically_testable=False,
            sampling_unit="participant",
            parameter_uncertainty_propagated=True,
            outcome_uncertainty_propagated=True,
            observed_outcomes_preserved=True,
            analysis_terms_in_imputation_model=None,  # depends on the analysis
            longitudinal_dependence_modeled=True,  # unstructured Sigma
            analysis_nested_in_imputation_model=None,
            congeniality_status=(
                "conditionally supported: mean model saturated by wave; "
                "analyses linear in the declared predictors and wave are "
                "nested in the imputation model"
            ),
            pooling_method="Rubin",
            mnar_sensitivity_performed=self.delta is not None,
            supported_outcome_types=("continuous",),
            notes=(
                "Exact conjugate data augmentation under the Jeffreys prior "
                "(Schafer 1997); imputations come from one chain separated "
                f"by thin={self.thin} sweeps after burn_in={self.burn_in}."
            ),
        )

    # -- assembly ---------------------------------------------------------

    def _wide_arrays(self, data: LongitudinalData):
        if data.outcome_type != "continuous":
            raise ValueError(
                "JointGaussianImputer supports continuous outcomes only; "
                f"got outcome_type={data.outcome_type!r}"
            )
        frame = data.frame
        # sorted to match LongitudinalData's (id, time) row order, so that
        # flattened draws align with completed_with()
        waves = sorted(
            data.times
            if data.times is not None
            else frame[data.time_col].unique().tolist()
        )
        j = len(waves)
        if j < 2:
            raise ValueError("need at least 2 waves")

        y_wide = frame.pivot(
            index=data.id_col, columns=data.time_col, values=data.outcome_col
        )
        missing_rows = y_wide.isna().all(axis=1)
        if set(y_wide.columns) != set(waves) or y_wide.shape != (
            data.n_participants,
            j,
        ):
            raise ValueError("unexpected wide shape")
        counts = frame.groupby(data.id_col, sort=True).size()
        if (counts != j).any():
            bad = counts[counts != j].index.tolist()[:5]
            raise ValueError(
                f"participants without a row for every design wave, e.g. {bad}; "
                "the joint Gaussian imputer requires a complete row grid "
                "(missing outcomes are fine, missing rows are not)"
            )
        y_wide = y_wide.loc[sorted(y_wide.index), waves]

        for col in data.predictor_cols:
            per_id = frame.groupby(data.id_col, sort=True)[col].nunique()
            if (per_id > 1).any():
                raise ValueError(
                    f"predictor {col!r} varies within participant; the joint "
                    "Gaussian imputer requires participant-level predictors"
                )
        x_frame = (
            frame.drop_duplicates(data.id_col)
            .set_index(data.id_col)
            .loc[y_wide.index, list(data.predictor_cols)]
        )
        try:
            x = x_frame.to_numpy(dtype=float)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                "predictors must be numeric for the joint Gaussian imputer; "
                "encode categories as indicator columns"
            ) from exc

        n = len(y_wide)
        x = np.column_stack([np.ones(n), x])
        k = x.shape[1]
        if n - k < j:
            raise ValueError(
                f"posterior for Sigma is improper: need n - K >= J, got "
                f"n={n}, K={k}, J={j}"
            )
        _ = missing_rows  # participants may miss every wave; MAR handles it
        return y_wide.to_numpy(dtype=float), x, waves

    # -- data augmentation ------------------------------------------------

    @staticmethod
    def _initial_fill(y: np.ndarray, x: np.ndarray) -> np.ndarray:
        filled = y.copy()
        for j in range(y.shape[1]):
            miss = np.isnan(y[:, j])
            if not miss.any():
                continue
            obs = ~miss
            if obs.sum() < x.shape[1]:
                raise ValueError(
                    f"wave index {j} has fewer observed outcomes than "
                    "regression columns"
                )
            coef, *_ = np.linalg.lstsq(x[obs], y[obs, j], rcond=None)
            filled[miss, j] = x[miss] @ coef
        return filled

    @staticmethod
    def _draw_parameters(y_complete, x, xtx_inv, chol_xtx_inv, rng):
        n, j = y_complete.shape
        k = x.shape[1]
        b_hat = xtx_inv @ x.T @ y_complete
        resid = y_complete - x @ b_hat
        s = resid.T @ resid
        sigma = stats.invwishart.rvs(df=n - k, scale=s, random_state=rng)
        sigma = np.atleast_2d(sigma)
        z = rng.standard_normal((k, j))
        b = b_hat + chol_xtx_inv @ z @ np.linalg.cholesky(sigma).T
        return b, sigma

    @staticmethod
    def _impute_step(y, mask, mu, sigma, rng):
        """Draw Y_mis | Y_obs, B, Sigma row by row (conditional MVN)."""
        out = y.copy()
        for i in np.flatnonzero(mask.any(axis=1)):
            mis = mask[i]
            obs = ~mis
            if obs.any():
                s_oo = sigma[np.ix_(obs, obs)]
                s_mo = sigma[np.ix_(mis, obs)]
                solve = np.linalg.solve(s_oo, y[i, obs] - mu[i, obs])
                cond_mean = mu[i, mis] + s_mo @ solve
                cond_cov = sigma[np.ix_(mis, mis)] - s_mo @ np.linalg.solve(
                    s_oo, s_mo.T
                )
                cond_cov = 0.5 * (cond_cov + cond_cov.T)
            else:
                cond_mean = mu[i, mis]
                cond_cov = sigma[np.ix_(mis, mis)]
            chol = np.linalg.cholesky(cond_cov)
            out[i, mis] = cond_mean + chol @ rng.standard_normal(int(mis.sum()))
        return out

    def impute(
        self,
        data: LongitudinalData,
        m: int,
        random_state: np.random.Generator,
    ) -> CompletedDatasetCollection:
        if m < 2:
            raise ValueError("m must be >= 2 for multiple imputation")
        rng = random_state
        y, x, waves = self._wide_arrays(data)
        mask = np.isnan(y)

        xtx_inv = np.linalg.inv(x.T @ x)
        chol_xtx_inv = np.linalg.cholesky(xtx_inv)

        current = self._initial_fill(y, x)
        completed_frames = []
        kept = 0
        sweeps_until_keep = self.burn_in
        while kept < m:
            for _ in range(max(sweeps_until_keep, 1)):
                b, sigma = self._draw_parameters(
                    current, x, xtx_inv, chol_xtx_inv, rng
                )
                mu = x @ b
                current = self._impute_step(y, mask, mu, sigma, rng)
            sweeps_until_keep = self.thin

            draw = current[mask]
            if self.delta is not None:
                draw = draw + self.delta.delta
            # imputed values align with LongitudinalData's (id, time) order:
            # y is participant-sorted rows x design-wave columns, and mask
            # flattens row-major exactly like the sorted long frame
            completed_frames.append(data.completed_with(draw))
            kept += 1

        return CompletedDatasetCollection(
            data,
            completed_frames,
            declaration=self.declaration,
            metadata={
                "imputer": "JointGaussianImputer",
                "burn_in": self.burn_in,
                "thin": self.thin,
                "waves": waves,
                "delta": None if self.delta is None else self.delta.delta,
            },
        )
