"""Joint Gaussian reference imputer (Schafer 1997's NORM with regressors).

The analytically transparent backend: participant i's response vector over
the J design waves follows a multivariate regression

    Y_i = B' x_i + e_i,        e_i ~ N(0, Sigma),

with participant-level predictors x_i (intercept added automatically),
wave-specific coefficients for every predictor, and unstructured Sigma.
Because every predictor gets its own coefficient at every wave, the mean
model is fully saturated in time: exposure-by-wave interactions are always
present (A8), and any analysis linear in these predictors and time is
nested in the imputation model.

Imputations are posterior-predictive draws (Proposition 2) generated by
Tanner-Wong data augmentation with the *exact* conjugate conditionals under
the Jeffreys prior p(B, Sigma) ~ |Sigma|^-(J+1)/2:

    I-step:  Y_mis | B, Sigma      — conditional multivariate normal
    P-step:  Sigma | Y_complete    ~ InverseWishart(n - K, S)
             B | Sigma, Y_complete ~ MatrixNormal(B_hat, (X'X)^-1, Sigma)

Both parameter and outcome uncertainty are propagated (A6). Kept
imputations come from a single chain separated by `thin` sweeps after
`burn_in`; every run reports single-chain autocorrelation and
effective-sample-size diagnostics (`GaussianChainDiagnostics`) so the
adequacy of `burn_in`/`thin` is inspected rather than asserted. Wave order
follows the declared design order, never a re-sort.

Scope: continuous outcomes; a complete participant-by-wave row grid
(missing outcomes allowed, missing rows not); predictors constant within
participant. Time-varying predictors need the GLMM backends.
"""

from __future__ import annotations

from typing import Any

import numpy as np
from scipy import stats

from ..contracts import ValidityDeclaration
from ..data import CompletedDatasetCollection, LongitudinalData
from ..diagnostics import GaussianChainDiagnostics
from ..scenarios import DeltaAdjustment
from .base import BaseFit, BaseImputer, data_fingerprint, normalize_random_state

__all__ = ["JointGaussianImputer", "JointGaussianFit"]


def _lag1_autocorrelation(series: np.ndarray) -> float:
    if len(series) < 3:
        return float("nan")
    a = series - series.mean()
    denom = float(a @ a)
    if denom == 0.0:
        return 0.0
    return float(a[:-1] @ a[1:] / denom)


class JointGaussianImputer(BaseImputer):
    """Posterior-predictive joint Gaussian imputation for fixed-wave data.

    Parameters
    ----------
    burn_in:
        Data-augmentation sweeps discarded before the first kept imputation.
    thin:
        Sweeps between successive kept imputations.
    delta:
        Default :class:`DeltaAdjustment` scenario; ``fit(...).impute(...,
        delta=...)`` overrides per run. For the identity link the
        ``linear_predictor`` and ``outcome`` scales coincide: imputed draws
        are shifted by ``delta``.
    allow_undeclared_times:
        Backends imputing longitudinal dropout need the declared design
        grid (``LongitudinalData(times=...)``) — absent rows cannot be
        imputed. Pass ``True`` to accept data without declared times, in
        which case the observed times are treated as the full design.
    """

    def __init__(
        self,
        *,
        burn_in: int = 500,
        thin: int = 100,
        delta: DeltaAdjustment | None = None,
        allow_undeclared_times: bool = False,
    ) -> None:
        if burn_in < 0 or thin < 1:
            raise ValueError("burn_in must be >= 0 and thin >= 1")
        self.burn_in = burn_in
        self.thin = thin
        self.delta = delta
        self.allow_undeclared_times = allow_undeclared_times

    @property
    def declaration(self) -> ValidityDeclaration:
        return self._declaration(self.delta)

    def _declaration(self, delta: DeltaAdjustment | None) -> ValidityDeclaration:
        return ValidityDeclaration(
            missingness_assumption=(
                "MAR" if delta is None else f"MNAR(delta={delta.delta})"
            ),
            mar_empirically_testable=False,
            sampling_unit="participant",
            parameter_uncertainty_propagated=True,
            outcome_uncertainty_propagated=True,
            observed_outcomes_preserved=True,
            analysis_terms_in_imputation_model=None,  # depends on the analysis
            longitudinal_dependence_modeled=True,  # unstructured Sigma
            analysis_nested_in_imputation_model=None,
            congeniality_status=(
                "conditionally supported: mean model saturated by wave; "
                "analyses linear in the declared predictors and wave are "
                "nested in the imputation model"
            ),
            pooling_method="Rubin",
            mnar_sensitivity_performed=delta is not None,
            supported_outcome_types=("continuous",),
            notes=(
                "Exact conjugate data augmentation under the Jeffreys prior "
                "(Schafer 1997); kept imputations come from one chain "
                f"separated by thin={self.thin} sweeps after "
                f"burn_in={self.burn_in} — judge adequacy from the run's "
                "chain diagnostics, not from the defaults."
            ),
        )

    # -- assembly ---------------------------------------------------------

    def _wide_arrays(self, data: LongitudinalData):
        if data.outcome_type != "continuous":
            raise ValueError(
                "JointGaussianImputer supports continuous outcomes only; "
                f"got outcome_type={data.outcome_type!r}"
            )
        if data.times is None and not self.allow_undeclared_times:
            raise ValueError(
                "declare the design grid (LongitudinalData(times=...)) so "
                "absent rows are caught before imputation, or construct the "
                "imputer with allow_undeclared_times=True to treat the "
                "observed times as the full design"
            )
        frame = data.frame
        # declared design order takes precedence over natural sorting
        waves = list(data.times) if data.times is not None else list(
            data.observed_times()
        )
        j = len(waves)
        if j < 2:
            raise ValueError("need at least 2 waves")

        # participant order comes from the validated long frame itself —
        # never re-sorted (ordered categorical IDs sort differently from
        # their labels, which silently misaligned imputations before)
        participant_order = frame[data.id_col].drop_duplicates().tolist()
        y_wide = frame.pivot(
            index=data.id_col, columns=data.time_col, values=data.outcome_col
        ).reindex(index=participant_order, columns=waves)
        if y_wide.isna().to_numpy().sum() != data.n_missing or y_wide.shape != (
            data.n_participants,
            j,
        ):
            raise ValueError(
                "participants without a row for every design wave; the joint "
                "Gaussian imputer requires a complete row grid "
                "(missing outcomes are fine, missing rows are not)"
            )

        for col in data.predictor_cols:
            per_id = frame.groupby(data.id_col, sort=False, observed=True)[
                col
            ].nunique()
            if (per_id > 1).any():
                raise ValueError(
                    f"predictor {col!r} varies within participant; the joint "
                    "Gaussian imputer requires participant-level predictors"
                )
        x_frame = (
            frame.drop_duplicates(data.id_col)
            .set_index(data.id_col)
            .reindex(participant_order)[list(data.predictor_cols)]
        )
        try:
            x = x_frame.to_numpy(dtype=float)
        except (TypeError, ValueError) as exc:
            raise ValueError(
                "predictors must be numeric for the joint Gaussian imputer; "
                "encode categories as indicator columns"
            ) from exc

        n = len(y_wide)
        x = np.column_stack([np.ones(n), x])
        if np.linalg.matrix_rank(x) < x.shape[1]:
            raise ValueError(
                "Gaussian imputation design matrix is rank deficient"
            )
        k = x.shape[1]
        if n - k < j:
            raise ValueError(
                f"posterior for Sigma is improper: need n - K >= J, got "
                f"n={n}, K={k}, J={j}"
            )
        return y_wide.to_numpy(dtype=float), x, waves

    def fit(self, data: LongitudinalData) -> "JointGaussianFit":
        y, x, waves = self._wide_arrays(data)
        # mechanical invariant: the flattened wide mask must equal the
        # validated long mask, in order
        if not np.array_equal(
            np.isnan(y).ravel(), data.missing_mask.to_numpy()
        ):
            raise RuntimeError(
                "internal wide/long missing-value alignment failed"
            )
        self._initial_fill(y, x)  # fail at fit time, not first impute
        return JointGaussianFit(self, data, y, x, waves)

    # -- draws (used by the fit object) -----------------------------------

    @staticmethod
    def _initial_fill(y: np.ndarray, x: np.ndarray) -> np.ndarray:
        filled = y.copy()
        for j in range(y.shape[1]):
            miss = np.isnan(y[:, j])
            if not miss.any():
                continue
            obs = ~miss
            if obs.sum() < x.shape[1]:
                raise ValueError(
                    f"wave index {j} has fewer observed outcomes than "
                    "regression columns"
                )
            coef, *_ = np.linalg.lstsq(x[obs], y[obs, j], rcond=None)
            filled[miss, j] = x[miss] @ coef
        return filled

    @staticmethod
    def _draw_parameters(y_complete, x, xtx_inv, chol_xtx_inv, rng):
        n, j = y_complete.shape
        k = x.shape[1]
        b_hat = xtx_inv @ x.T @ y_complete
        resid = y_complete - x @ b_hat
        s = resid.T @ resid
        sigma = stats.invwishart.rvs(df=n - k, scale=s, random_state=rng)
        sigma = np.atleast_2d(sigma)
        z = rng.standard_normal((k, j))
        b = b_hat + chol_xtx_inv @ z @ np.linalg.cholesky(sigma).T
        return b, sigma

    @staticmethod
    def _impute_step(y, mask, mu, sigma, rng):
        """Draw Y_mis | Y_obs, B, Sigma row by row (conditional MVN)."""
        out = y.copy()
        for i in np.flatnonzero(mask.any(axis=1)):
            mis = mask[i]
            obs = ~mis
            if obs.any():
                s_oo = sigma[np.ix_(obs, obs)]
                s_mo = sigma[np.ix_(mis, obs)]
                solve = np.linalg.solve(s_oo, y[i, obs] - mu[i, obs])
                cond_mean = mu[i, mis] + s_mo @ solve
                cond_cov = sigma[np.ix_(mis, mis)] - s_mo @ np.linalg.solve(
                    s_oo, s_mo.T
                )
                cond_cov = 0.5 * (cond_cov + cond_cov.T)
            else:
                cond_mean = mu[i, mis]
                cond_cov = sigma[np.ix_(mis, mis)]
            eigval, eigvec = np.linalg.eigh(cond_cov)
            scale = max(float(np.max(np.abs(eigval))), np.finfo(float).tiny)
            if eigval.min() < -1e-10 * scale:
                raise RuntimeError(
                    "conditional Gaussian covariance is materially indefinite"
                )
            factor = eigvec @ np.diag(np.sqrt(np.maximum(eigval, 0.0)))
            out[i, mis] = cond_mean + factor @ rng.standard_normal(int(mis.sum()))
        return out


class JointGaussianFit(BaseFit):
    """Validated design and precomputations for one dataset.

    Each :meth:`impute` call runs a fresh data-augmentation chain (the
    conjugate conditionals need no upfront estimation), so scenario runs
    with the same ``random_state`` share identical underlying draws — a
    delta scenario differs from MAR only by the deterministic shift.
    """

    def __init__(self, imputer, data, y, x, waves):
        self._imputer = imputer
        self._data = data
        self._y = y
        self._x = x
        self._waves = waves
        self._xtx_inv = np.linalg.inv(x.T @ x)
        self._chol_xtx_inv = np.linalg.cholesky(self._xtx_inv)
        self.declaration = imputer.declaration
        self.data_fingerprint = data_fingerprint(data)
        self.model_specification: dict[str, Any] = {
            "backend": "JointGaussianImputer",
            "waves": list(waves),
            "predictors": list(data.predictor_cols),
            "mean_model": "wave-saturated multivariate regression",
            "covariance": "unstructured",
            "prior": "Jeffreys |Sigma|^-(J+1)/2",
            "burn_in": imputer.burn_in,
            "thin": imputer.thin,
        }
        self.diagnostics: GaussianChainDiagnostics | None = None  # per run

    def impute(
        self,
        m: int,
        random_state: int | np.random.Generator,
        *,
        delta: DeltaAdjustment | None = None,
    ) -> CompletedDatasetCollection:
        if m < 2:
            raise ValueError("m must be >= 2 for multiple imputation")
        imp = self._imputer
        delta = delta if delta is not None else imp.delta
        if delta is not None and getattr(delta, "is_targeted", False):
            raise NotImplementedError(
                "targeted delta rules (where/times) are not yet supported "
                "by this backend; use a scalar DeltaAdjustment"
            )
        rng, rng_record = normalize_random_state(random_state)
        data, y, x = self._data, self._y, self._x
        mask = np.isnan(y)

        current = imp._initial_fill(y, x)
        trace: list[float] = []
        completed_frames = []
        kept_sweeps: list[int] = []
        kept = 0
        sweep = 0
        sweeps_until_keep = imp.burn_in
        while kept < m:
            for _ in range(max(sweeps_until_keep, 1)):
                b, sigma = imp._draw_parameters(
                    current, x, self._xtx_inv, self._chol_xtx_inv, rng
                )
                mu = x @ b
                current = imp._impute_step(y, mask, mu, sigma, rng)
                trace.append(float(np.linalg.slogdet(sigma)[1]))
                sweep += 1
            sweeps_until_keep = imp.thin
            kept_sweeps.append(sweep - 1)

            draw = current[mask]
            if delta is not None:
                draw = draw + delta.delta
            # imputed values align with LongitudinalData's (id, time) order:
            # y is participant-sorted rows x declared-order wave columns, and
            # mask flattens row-major exactly like the stored long frame
            completed_frames.append(data.completed_with(draw))
            kept += 1

        post = np.asarray(trace[imp.burn_in :])
        rho = _lag1_autocorrelation(post)
        ess = (
            float(len(post)) * (1.0 - rho) / (1.0 + rho)
            if np.isfinite(rho) and rho > -1.0
            else float("nan")
        )
        kept_trace = np.asarray(trace)[kept_sweeps]
        diagnostics = GaussianChainDiagnostics(
            n_sweeps=sweep,
            burn_in=imp.burn_in,
            thin=imp.thin,
            m=m,
            trace_lag1_autocorrelation=rho,
            trace_ess=ess,
            kept_lag1_autocorrelation=_lag1_autocorrelation(kept_trace),
        )
        self.diagnostics = diagnostics

        return CompletedDatasetCollection(
            data,
            completed_frames,
            declaration=imp._declaration(delta),
            metadata={
                "imputer": "JointGaussianImputer",
                "model_specification": dict(self.model_specification),
                "data_fingerprint": self.data_fingerprint,
                "random_state": rng_record,
                "delta": None if delta is None else delta.delta,
                "diagnostics": diagnostics,
            },
        )
